### ISSUE TITLE
Atom v1.13.0 warning

### ISSUE THREAD

**Issue by gsklee** [smlombardi/oceanic-next-syntax#12] opened 2017-01-11 06:08 UTC
After updating Atom to v1.13.0, there's a fairly large warning about deprecated selectors that should no longer be used.

**Comment by ryancole** [comment] 2017-01-11 17:29
Just for completeness sake, below is the contents of what I'm seeing on the deprecation warning ...

```
oceanic-next\index.less
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor, :host => atom-text-editor,atom-text-editor
atom-text-editor .gutter, :host .gutter => atom-text-editor .gutter,atom-text-editor .gutter
atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line => atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line
atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection => atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection
atom-text-editor .wrap-guide, :host .wrap-guide => atom-text-editor .wrap-guide,atom-text-editor .wrap-guide
atom-text-editor .indent-guide, :host .indent-guide => atom-text-editor .indent-guide,atom-text-editor .indent-guide
atom-text-editor .invisible-character, :host .invisible-character => atom-text-editor .invisible-character,atom-text-editor .invisible-character
atom-text-editor .search-results .marker .region, :host .search-results .marker .region => atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region
atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region => atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region
atom-text-editor.is-focused .cursor, :host(.is-focused) .cursor => atom-text-editor.is-focused .cursor,atom-text-editor .cursor
atom-text-editor.is-focused .selection .region, :host(.is-focused) .selection .region => atom-text-editor.is-focused .selection .region,atom-text-editor .selection .region
atom-text-editor.is-focused .line-number.cursor-line-no-selection, atom-text-editor.is-focused .line.cursor-line, :host(.is-focused) .line-number.cursor-line-no-selection, :host(.is-focused) .line.cursor-line => atom-text-editor.is-focused .line-number.cursor-line-no-selection, atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line
.comment, .punctuation.definition.comment => .syntax--comment, .syntax--punctuation.syntax--definition.syntax--comment
.variable => .syntax--variable
.function > .variable => .syntax--function > .syntax--variable
.keyword, .storage.modifier, .storage.type => .syntax--keyword, .syntax--storage.syntax--modifier, .syntax--storage.syntax--type
.keyword.operator, .constant.other.color, .punctuation, .punctuation.string, .meta.tag, .punctuation.definition.tag, .punctuation.separator.inheritance.php, .punctuation.definition.tag.html, .punctuation.definition.tag.begin.html, .punctuation.definition.tag.end.html => .syntax--keyword.syntax--operator, .syntax--constant.syntax--other.syntax--color, .syntax--punctuation, .syntax--punctuation.syntax--string, .syntax--meta.syntax--tag, .syntax--punctuation.syntax--definition.syntax--tag, .syntax--punctuation.syntax--separator.syntax--inheritance.syntax--php, .syntax--punctuation.syntax--definition.syntax--tag.syntax--html, .syntax--punctuation.syntax--definition.syntax--tag.syntax--begin.syntax--html, .syntax--punctuation.syntax--definition.syntax--tag.syntax--end.syntax--html
.entity.name.tag, .meta.tag.sgml, .markup.deleted.git_gutter => .syntax--entity.syntax--name.syntax--tag, .syntax--meta.syntax--tag.syntax--sgml, .syntax--markup.syntax--deleted.git_gutter
.entity.name.function, .meta.function-call, .support.function, .keyword.other.special-method, .meta.block-level => .syntax--entity.syntax--name.syntax--function, .syntax--meta.syntax--function-call, .syntax--support.syntax--function, .syntax--keyword.syntax--other.syntax--special-method, .syntax--meta.syntax--block-level
.support.other.variable, .string.other.link => .syntax--support.syntax--other.syntax--variable, .syntax--string.syntax--other.syntax--link
.constant.numeric, .constant.language, .support.constant, .constant.character, .variable.parameter, .punctuation.section.embedded, .keyword.other.unit => .syntax--constant.syntax--numeric, .syntax--constant.syntax--language, .syntax--support.syntax--constant, .syntax--constant.syntax--character, .syntax--variable.syntax--parameter, .syntax--punctuation.syntax--section.syntax--embedded, .syntax--keyword.syntax--other.syntax--unit
.string, .variable.quoted.elixir, .constant.other.symbol, .entity.other.inherited-class, .markup.heading, .markup.inserted.git_gutter => .syntax--string, .syntax--variable.syntax--quoted.syntax--elixir, .syntax--constant.syntax--other.syntax--symbol, .syntax--entity.syntax--other.syntax--inherited-class, .syntax--markup.syntax--heading, .syntax--markup.syntax--inserted.git_gutter
.variable.constant.elixir, .entity.name.type, .entity.name.class, .entity.name.type.class, .support.type, .support.class, .support.orther.namespace.use.php, .meta.use.php, .support.other.namespace.php, .markup.changed.git_gutter => .syntax--variable.syntax--constant.syntax--elixir, .syntax--entity.syntax--name.syntax--type, .syntax--entity.syntax--name.syntax--class, .syntax--entity.syntax--name.syntax--type.syntax--class, .syntax--support.syntax--type, .syntax--support.syntax--class, .syntax--support.orther.syntax--namespace.syntax--use.syntax--php, .syntax--meta.syntax--use.syntax--php, .syntax--support.syntax--other.syntax--namespace.syntax--php, .syntax--markup.syntax--changed.git_gutter
.entity.name.module.js, .variable.import.parameter.js, .variable.other.class.js => .syntax--entity.syntax--name.syntax--module.syntax--js, .syntax--variable.syntax--import.syntax--parameter.syntax--js, .syntax--variable.syntax--other.syntax--class.syntax--js
.variable.language => .syntax--variable.syntax--language
.entity.name.method.js => .syntax--entity.syntax--name.syntax--method.syntax--js
.meta.method.js => .syntax--meta.syntax--method.syntax--js
.entity.other.attribute-name => .syntax--entity.syntax--other.syntax--attribute-name
.markup.inserted => .syntax--markup.syntax--inserted
.markup.deleted => .syntax--markup.syntax--deleted
.markup.changed => .syntax--markup.syntax--changed
.string.regexp => .syntax--string.syntax--regexp
.constant.character.escape => .syntax--constant.syntax--character.syntax--escape
.constant.character.escape.css, .constant.character.escape.scss => .syntax--constant.syntax--character.syntax--escape.syntax--css, .syntax--constant.syntax--character.syntax--escape.syntax--scss
` .url ,
.link *,
.uri => .syntax--url *,
.syntax--link *,
.syntax--uri *`
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.
```

**Comment by natorojr** [comment] 2017-01-13 06:20
Duplicate of #14 
Can we close and consolidate this one?

**Comment by gsklee** [comment] 2017-01-13 06:37
@natorojr Per common bug triage process, #14 and #13 are the dupes of this ticket, not the other way around, unless the project owner determines there is significant info only present in a later ticket, or other similar reasons.

**Comment by natorojr** [comment] 2017-01-13 06:47
Thanks for note, @gsklee

I understand the typical process and would generally agree with you, _but_, in this particular case, I'd prefer to keep #14 open since that's the one that was automatically generated by Atom when you hit the "Report Issue" button in Atom's Deprecation Cop interface. As such, every other Atom user that hits the "Report Issue" button will be taken to #14 automatically, hopefully preventing the proliferation of unnecessary duplicate bugs.

As you said, the project owner can decide.

![screen shot 2017-01-12 at 10 42 52 pm](https://cloud.githubusercontent.com/assets/1237186/21920921/067afeb4-d919-11e6-90b3-74b890d74ae8.png)

**Closed as completed** 2017-01-13 14:49 UTC
